blank_issues_enabled: false
contact_links:
  - name: Request a feature
    url: https://github.com/Nilanth/laravel-react-redux/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a bug
    url: https://github.com/laravel-react-redux/issues/new
    about: Report a reproducable bug
